### ISSUE TITLE
feat: 新增保存按鈕

### ISSUE THREAD

**Issue by konnokai** [lintx/MapleStoryTools#1]
有時會遇到自動保存會失敗，不知道是哪邊沒觸發到保存所以每次重開網頁後都會讀出錯的資料
只能在設定完後透過分享功能把數值複製起來後更改 Local Storage 內的資料來使用

目前想法是可以在角色的屬性設定頁面最下面新增保存按鈕，或是放在附圖中的最右側
![image](https://github.com/user-attachments/assets/234ed411-b98a-4f90-9066-d2b763ef419c)

但 Buff 設定頁面的自訂 Buff 保存是正常的，以防萬一也可以新增一個保存按鈕在 Buff 頁面

**Comment by lintx** [comment]
保存問題不是由自動保存引起的，目前也在追這個問題，但是沒能在我這邊進行復現

**Comment by KeineKuni** [comment]
不會自動保存

**Comment by lintx** [comment]
已增加保存按鈕，優化了保存邏輯
