### ISSUE TITLE
hexa屬性計算問題

### ISSUE THREAD

**Issue by Louis208908** [lintx/MapleStoryTools#3]
我在進行hexa屬性的計算的時候發現了一些問題 就是  在最上面我們已經計算出了原有的防後B暴攻
這個數字跟   hexa屬性計算是 你選擇與我現在相同的詞條時計算出的防後B暴攻有出入
![image](https://github.com/user-attachments/assets/29105073-5b76-432e-8aeb-09a6acc16c10)
![image](https://github.com/user-attachments/assets/9786d27a-316a-427c-b8bd-8dc84775cad3)

**Comment by lintx** [comment]
已經重新整理邏輯
