### ISSUE TITLE
極限屬性計算

### ISSUE THREAD

**Issue by Louis208908** [lintx/MapleStoryTools#4]
針對凱內西斯、陰陽師等職業，可能會在極限屬性上面花費一定點數去增加PP、DF、靈力的數值

目前極限屬性計算的部分無法涵蓋這一項數值，只能夠在其餘不相關的點數上點10點來模擬增加PP、DF、靈力的部分

**Comment by lintx** [comment]
沒有理解

**Comment by Louis208908** [comment]
![image](https://github.com/user-attachments/assets/2b4effcd-ff24-4873-b431-9949f496ca4f)
有些職業會需要點選圖中的這一個極限屬性 但現在的計算機並沒有這個選項讓他們選擇  

怎麼會直接closed as completed呢XD

**Comment by lintx** [comment]
因為這個屬性不會影響到攻擊數值，直接無視就好，就好像暴擊率一樣，先正常點，點完後在計算機裡面填寫個條目當前等級和剩餘點數後計算即可，計算機提供的條目，填寫等級後，計算時會計算使用了多少點屬性點，在計算一開始時會將這些屬性扣除，然後將屬性點加上去，最後才開始模擬計算
