### ISSUE TITLE
極限屬性計算問題

### ISSUE THREAD

**Issue by Louis208908** [lintx/MapleStoryTools#6]
如圖，極限屬性計算後的防後暴B攻應該出現了問題  
用改良後的這個配點重新計算也不會出現這麼大的提升
![image](https://github.com/user-attachments/assets/1e9294e8-2e68-4348-9f34-4c9069dd2554)

![image](https://github.com/user-attachments/assets/16f8ccdf-eb30-4620-aea3-cb07afd56f2c)

**Comment by lintx** [comment]
請貼出素質連結和超級屬性計算時填寫的數值，我確認下

**Comment by Louis208908** [comment]
https://lintx.github.io/MapleStoryTools/#/stat-calc/import/3,445,103.6,133,0,0,0,0,0,0,94.85,6183,28590,672,212,289,3698,440,121,12,4673,0,119,94,0,0,0
![image](https://github.com/user-attachments/assets/37356be4-4535-403b-8ccf-9155f01245b8)

**Comment by lintx** [comment]
已修復
